name: Build_VitePress

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.20.0
      - uses: actions/setup-node@v3
        with:
          node-version: 19.3.0 
          cache: "pnpm"
      - run: pnpm add vitepress vue sass
      - run: pnpm up --latest
      - run: pnpm docs:build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          PUBLISH_BRANCH: source
          publish_dir: docs/.vitepress/dist
